---
- hosts: demo
  become: yes
  tasks:
    - name: installing apache
      yum: 
       name: "apache2"
       state: "present"
    - name: starting service
       name: apach2
       state: started
       enabled: True
    - name: copy
       copy:
          src: index.html
          dest: /var/www/html/
