---
- hosts: demo
  become: yes
  tasks:
    - name: installing apache
      yum: 
       name: "apache2"
       state: "present"
    - name: starting service
      service:
       name: apache2
       state: started
       enabled: True
    - name: deploying
      template:
       src: index.html
       dest: /var/www/html/
