---
- hosts: demo
  become: yes
  tasks:
    - name: installing apache
      apt: 
       name: "apache2-bin"
       state: "present"
    - name: starting service
      service:
       name: "apache2-bin"
       state: "started"
       enabled: True
    - name: deploying
      template:
       src: index.html
       dest: /var/www/html/
